import type { Metadata } from "next";

import "./globals.css";

import { fontBody, fontHeading, fontMono } from "@/lib/config";
import { cn } from "@/lib/utils";
import { SupabaseClientProvider } from "@/provider/supabase-provider";
import { ThemeProvider } from "@/provider/theme-provider";

export const metadata: Metadata = {
  title: "letters",
  description: "Generated by appncy",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("antialiased", fontBody.variable, fontMono.variable, fontHeading.variable)}>
        <SupabaseClientProvider>
          <ThemeProvider>{children}
            <div id="pruebita"></div>
          </ThemeProvider>
        </SupabaseClientProvider>
      </body>
    </html>
  );
}
