import type { Metadata } from 'next';

import './globals.css';

import { ViewTransitions } from 'next-view-transitions';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import { Suspense } from 'react';

import { fontBody, fontHeading, fontMono } from '@/lib/config';
import { cn } from '@/lib/utils';
import { ErrorProvider } from '@/provider/errors-provider';
import { SupabaseClientProvider } from '@/provider/supabase-provider';
import { ThemeProvider } from '@/provider/theme-provider';

export const metadata: Metadata = {
  title: {
    default: 'letters',
    template: '%s | letters',
  },
  description: 'Generated by appncy',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ViewTransitions>
      <html suppressHydrationWarning lang="en">
        <body className={cn('antialiased', fontBody.variable, fontMono.variable, fontHeading.variable)}>
          <Suspense>
            <NuqsAdapter>
              <ErrorProvider>
                <SupabaseClientProvider>
                  <ThemeProvider>{children}</ThemeProvider>
                </SupabaseClientProvider>
              </ErrorProvider>
            </NuqsAdapter>
          </Suspense>
        </body>
      </html>
    </ViewTransitions>
  );
}
